language: java
install:
  - wget -c http://apache.stu.edu.tw//jmeter/binaries/apache-jmeter-3.2.tgz
  - tar -xf apache-jmeter-3.2.tgz
before_script:
  - ls -al
script:
  - ant -buildfile build.xml -Dtestpath=$HOME/JmeterExample/http -Dtest="google" -Dbasedir=$HOME/JmeterExample/http -Djmeter.home="$HOME/JmeterExample/apache-jmeter-3.2"

