language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
install:
  - wget -c http://apache.stu.edu.tw//jmeter/binaries/apache-jmeter-3.2.tgz
  - tar -xf apache-jmeter-3.2.tgz
before_script:
  - ls -al
  - cp /home/travis/build/dariachen/JmeterExample/apache-jmeter-3.2/extras/ant-jmeter-1.1.1.jar ./
  - cp /home/travis/build/dariachen/JmeterExample/apache-jmeter-3.2/extras/jmeter-results-detail-report_21.xsl ./
  - cp /home/travis/build/dariachen/JmeterExample/apache-jmeter-3.2/extras/collapse.png ./
  - cp /home/travis/build/dariachen/JmeterExample/apache-jmeter-3.2/extras/expand.png ./
  - ls -al
branches:
  only:
  - master
  - feature/travis-testing
script:
  - jdk_switcher use oraclejdk8
  - ant -buildfile build.xml -Dtestpath=./http -Dtest="google_02" -Dbasedir=/home/travis/build/dariachen/JmeterExample -Djmeter.home="/home/travis/build/dariachen/JmeterExample/apache-jmeter-3.2"
  - cd ./http
  - chmod 744 parse_result.sh
  - sh parse_result.sh
  - cd ..
after_success:
  addons:
    artifacts:
      s3_region: ap-northeast-1
      working_dir: ./http/result


